DROP TABLE IF EXISTS trades CASCADE;
DROP TABLE IF EXISTS positions CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS securities CASCADE;

-- \i src/database/schema.sql

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  balance DECIMAL(15,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE securities (
  symbol TEXT PRIMARY KEY,
  price DECIMAL(15,2) NOT NULL,
  status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  security TEXT REFERENCES securities(symbol),
  order_type VARCHAR(10) NOT NULL,
  buy_sell VARCHAR(4) NOT NULL,
  quantity DECIMAL(15,2) NOT NULL,
  price DECIMAL(15,2) NOT NULL,
  status VARCHAR(10) DEFAULT 'ACTIVE',
  expiration_time DECIMAL(15,2),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE positions (
  user_id BIGINT REFERENCES users(id),
  security TEXT REFERENCES securities(symbol),
  quantity DECIMAL(15,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, security)
);

CREATE TABLE trades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buy_order_id BIGINT REFERENCES orders(id),
  sell_order_id BIGINT REFERENCES orders(id),
  security TEXT REFERENCES securities(symbol),
  quantity DECIMAL(15,2) NOT NULL,
  price DECIMAL(15,2) NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

INSERT INTO securities (symbol, price, status) VALUES
  ('AAPL', 150.00, 'ACTIVE'),
  ('MSFT', 330.00, 'ACTIVE'),
  ('GOOGL', 140.00, 'ACTIVE'),
  ('AMZN', 180.00, 'ACTIVE'),
  ('TSLA', 300.00, 'ACTIVE'),
  ('META', 300.00, 'ACTIVE'),
  ('NVDA', 400.00, 'ACTIVE'),
  ('RKLB', 20.00, 'ACTIVE'),
  ('RIVN', 15.00, 'ACTIVE'),
  ('PLTR', 53.00, 'ACTIVE')
ON CONFLICT (symbol) DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_security ON orders(security);
CREATE INDEX IF NOT EXISTS idx_positions_user_id ON positions(user_id);